import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <main className="flex-1">{children}</main>

        <footer className="mt-auto border-t border-gray-200 py-6 text-center text-sm text-gray-500">
          <p>© 2026 GlownUp</p>

          <div className="mt-2 flex justify-center gap-4">
            <a href="/" className="hover:text-black">
              Home
            </a>

            <a href="/privacy" className="hover:text-black">
              Privacy
            </a>

            <a href="/terms" className="hover:text-black">
              Terms
            </a>

            <a href="mailto:fsdsanalytics@gmail.com" className="hover:text-black">
              Contact
            </a>
          </div>
        </footer>
        <Analytics />
      </body>
    </html>
  );
}
