type TransformationCardProps = {
    originalImageUrl: string;
    generatedImageUrl: string;
    title?: string;
  };
  
  export default function TransformationCard({
    originalImageUrl,
    generatedImageUrl,
    title = "YOUR FUTURE PHYSIQUE",
  }: TransformationCardProps) {
    return (
      <div className="mx-auto aspect-square w-full max-w-[720px] rounded-3xl bg-white p-6 shadow-sm">
        <div className="flex h-full flex-col">
          <div className="pb-4 text-center">
            <h2 className="text-2xl font-semibold tracking-tight">{title}</h2>
          </div>
  
          <div className="grid flex-1 grid-cols-2 gap-4">
            <div className="flex flex-col">
              <p className="mb-2 text-center text-sm font-medium text-gray-500">
                BEFORE
              </p>
              <div className="flex-1 overflow-hidden rounded-2xl bg-gray-100 p-2">
                <img
                  src={originalImageUrl}
                  alt="Before"
                  className="h-full w-full object-contain"
                />
              </div>
            </div>
  
            <div className="flex flex-col">
              <p className="mb-2 text-center text-sm font-medium text-gray-500">
                AFTER
              </p>
              <div className="flex-1 overflow-hidden rounded-2xl bg-gray-100 p-2">
                <img
                  src={generatedImageUrl}
                  alt="After"
                  className="h-full w-full object-contain"
                />
              </div>
            </div>
          </div>
  
          <div className="pt-4 text-center text-sm text-gray-500">
            Generated by GlownUp
          </div>
        </div>
      </div>
    );
  }